name: Publish artifacts to Central

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:

jobs:
  publish:
    if: ${{ contains(github.event.head_commit.message, '[docs only]') == false }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4
        with:
          fetch-depth: 1000
          fetch-tags: true

      - name: Validate wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup Java 21
        if: inputs.version_task
        run: |
          echo "JAVA_HOME=$(echo $JAVA_HOME_21_X64)" >> "$GITHUB_ENV"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Publish
        run: ./gradlew publish closeAndReleaseSonatypeStagingRepository
        env:
          GPG_SUBKEY: ${{ secrets.GPG_SUBKEY }}
          GPG_SUBKEY_ID: ${{ secrets.GPG_SUBKEY_ID }}
          GPG_SUBKEY_PASSWORD: ${{ secrets.GPG_SUBKEY_PASSWORD }}
          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
