name: Deploy Images to GHCR

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:

jobs:
  push-image:
    if: ${{ contains(github.event.head_commit.message, '[docs only]') == false }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Run build with Gradle Wrapper
        run: ./gradlew :build :shadowJar :outputVersion

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Image'
        run: |
          docker build . --tag ghcr.io/neoforged/camelot:latest --tag ghcr.io/neoforged/camelot:${{ env.BOT_VERSION }}
          docker push ghcr.io/neoforged/camelot:latest
          docker push ghcr.io/neoforged/camelot:${{ env.BOT_VERSION }}
